langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: llama3.2:latest
    embedding-model:
      base-url: http://localhost:11434
      model-name: nomic-embed-text

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

app:
  rag:
    cache-path: ./rag-cache.json
    max-results: 5
    chunk-size: 512
    chunk-overlap: 0
